services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: book-advisor-db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: unless-stopped

  mongodb-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongodb

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: book-advisor-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "9090:9090"
    environment:
      PGADMIN_LISTEN_PORT: 9090
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_UI_AUTH: ${MAILPIT_LOGIN}:${MAILPIT_PASSWORD}

  proxy:
    image: lukasz408/proxy:1.0
    container_name: proxy
    ports:
      - "8000:8000"
    environment:
      TIMEOUT: 15000

volumes:
  mongo_data:
  postgres_data:
