spring:
  mongodb:
    uri: mongodb://mongo_user:mongo_password@localhost:27017/admin
    database: book-advisor-db
  datasource:
    url: jdbc:postgresql://localhost:5435/book-advisor-db
    username: postgres
    password: password
    hikari:
      pool-name: BookAdvisorHikariCP
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
        mail:
            smtp:
            auth: false
            starttls:
                enable: false
            debug: true

  cloud:
    openfeign:
      client:
        config:
          openLibraryClient:
            logger-level: basic
            url: https://openlibrary.org/

resilience4j:
  timelimiter:
    instances:
      search-openLibraryRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 6s
        timeoutDuration: 1s
  retry:
    instances:
      search-openLibraryRetry:
        max-attempts: 4
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        max-wait-duration: 5s
        retry-exceptions:
          - feign.RetryableException

logging:
  level:
    io.github.luksal.book.openlibrary: DEBUG

app:
  mail:
    from: noreply-book-advisor@gmail.com
    to: lukasz4088@gmail.com
